name: Publish Docker image
on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - "**.go"
      - go.sum
      - Dockerfile

  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - go.sum
      - Dockerfile

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Compile Clingo binary
        run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o clingo main.go

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set env variables
        run: |
          export BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          if [[ $BRANCH == "master" ]]; then
              echo "TAG=latest" >> "$GITHUB_ENV"
          else
              echo "TAG=test" >> "$GITHUB_ENV"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: nsavelyeva/clingo:${{env.TAG}}
